name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        Have an idea? Describe it below.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this solve? What's the motivation?
      placeholder: I find it frustrating when ...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any other approaches you've thought about?
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Mockups, examples, or references that help explain the idea.
    validations:
      required: false
